name 'formatron_elk'
version '0.1.0'
description 'Formatron ELK cookbook'
source_url 'https://github.com/formatron/elk-cookbook'
issues_url 'https://github.com/formatron/elk-cookbook/issues'
supports 'ubuntu'
depends 'formatron_elasticsearch'
depends 'formatron_logstash'
depends 'formatron_kibana'
